In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import arff
import os

## Data Cleaning

In [3]:
# Load the data.
dir_path = os.path.dirname(os.getcwd())
freq_data_path = os.path.join(dir_path, 'data/freMTPL2freq.arff')
sev_data_path = os.path.join(dir_path, 'data/freMTPL2sev.arff')

with open(freq_data_path) as f:
    freq_data = arff.load(f)
freq_df = pd.DataFrame(data=freq_data['data'], columns=[a[0] for a in freq_data['attributes']])

with open(sev_data_path) as f:
    sev_data = arff.load(f)
sev_df = pd.DataFrame(data=sev_data['data'], columns=[a[0] for a in sev_data['attributes']])

In [4]:
# Merge the frequency and severity data. 
df = pd.merge(freq_df, sev_df, on='IDpol', how='left')


# Convert the byte columns to categories.
for col in df.select_dtypes([object]):
    df[col] = df[col].apply(lambda x: x.decode() if isinstance(x, bytes) else x)
    df[col] = df[col].astype('category')


# Show the first rows.
df.head()

,IDpol,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region,ClaimAmount
0,1.0,1.0,0.10,D,5.0,0.0,55.0,50.0,B12,Regular,1217.0,R82,NaN
1,3.0,1.0,0.77,D,5.0,0.0,55.0,50.0,B12,Regular,1217.0,R82,NaN
2,5.0,1.0,0.75,B,6.0,2.0,52.0,50.0,B12,Diesel,54.0,R22,NaN
3,10.0,1.0,0.09,B,7.0,0.0,46.0,50.0,B12,Diesel,76.0,R72,NaN
4,11.0,1.0,0.84,B,7.0,0.0,46.0,50.0,B12,Diesel,76.0,R72,NaN

In [5]:
# Check if there are missing values.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679513 entries, 0 to 679512
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   IDpol        679513 non-null  float64
 1   ClaimNb      679513 non-null  float64
 2   Exposure     679513 non-null  float64
 3   Area         679513 non-null  category
 4   VehPower     679513 non-null  float64
 5   VehAge       679513 non-null  float64
 6   DrivAge      679513 non-null  float64
 7   BonusMalus   679513 non-null  float64
 8   VehBrand     679513 non-null  category
 9   VehGas       679513 non-null  category
 10  Density      679513 non-null  float64
 11  Region       679513 non-null  category
 12  ClaimAmount  26444 non-null   float64
dtypes: category(4), float64(9)
memory usage: 49.3 MB

In [6]:
# Change the column names for readibility 
df = df.rename(columns={
    'IDpol': 'id',
    'ClaimNb': 'n_claims',
    'Exposure': 'exposure',
    'DrivAge': 'driver_age',
    'VehAge': 'vehicle_age',
    'BonusMalus': 'bonus_malus',
    'Density': 'density',
    'Area': 'area',
    'VehPower': 'vehicle_power',
    'VehBrand': 'vehicle_brand',
    'VehGas': 'vehicle_gas',
    'Region': 'region',
    'ClaimAmount': 'claim_amount'
    })

In [7]:
df.columns

Index(['id', 'n_claims', 'exposure', 'area', 'vehicle_power', 'vehicle_age',
       'driver_age', 'bonus_malus', 'vehicle_brand', 'vehicle_gas', 'density',
       'region', 'claim_amount'],
      dtype='object')

In [8]:
# Sanity checks. We can see other features' validity from OpenML
print(((df['driver_age']<18) | (df['driver_age'] > 100)).any(),
    (df['density']<0).any(),
    (df['exposure'] <= 0).any()
    )

False False False

In [9]:
# Create the frequency column
df['frequency'] = df['n_claims'] / df['exposure']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679513 entries, 0 to 679512
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             679513 non-null  float64
 1   n_claims       679513 non-null  float64
 2   exposure       679513 non-null  float64
 3   area           679513 non-null  category
 4   vehicle_power  679513 non-null  float64
 5   vehicle_age    679513 non-null  float64
 6   driver_age     679513 non-null  float64
 7   bonus_malus    679513 non-null  float64
 8   vehicle_brand  679513 non-null  category
 9   vehicle_gas    679513 non-null  category
 10  density        679513 non-null  float64
 11  region         679513 non-null  category
 12  claim_amount   26444 non-null   float64
 13  frequency      679513 non-null  float64
dtypes: category(4), float64(10)
memory usage: 54.4 MB

In [11]:
# Fill the NaN values in claim_amount column with 0.
df['claim_amount'] = df['claim_amount'].fillna(0)

(df['claim_amount'] == 0).sum()

np.int64(653069)

In [12]:
# Create a csv file of the cleaned data.
df.to_csv(os.path.join(dir_path, 'data/cleaned_data.csv'))

In [13]:
# Load the clean data. From now on we are working on this dataframe.
df = pd.read_csv(os.path.join(dir_path, 'data/cleaned_data.csv'))

In [14]:
# Take a look at the first rows. 
df.head()

,Unnamed: 0,id,n_claims,exposure,area,vehicle_power,vehicle_age,driver_age,bonus_malus,vehicle_brand,vehicle_gas,density,region,claim_amount,frequency
0,0,1.0,1.0,0.10,D,5.0,0.0,55.0,50.0,B12,Regular,1217.0,R82,0.0,10.000000
1,1,3.0,1.0,0.77,D,5.0,0.0,55.0,50.0,B12,Regular,1217.0,R82,0.0,1.298701
2,2,5.0,1.0,0.75,B,6.0,2.0,52.0,50.0,B12,Diesel,54.0,R22,0.0,1.333333
3,3,10.0,1.0,0.09,B,7.0,0.0,46.0,50.0,B12,Diesel,76.0,R72,0.0,11.111111
4,4,11.0,1.0,0.84,B,7.0,0.0,46.0,50.0,B12,Diesel,76.0,R72,0.0,1.190476

In [15]:
# Drop the unnecessary column.
df = df.drop(columns='Unnamed: 0')

In [43]:
df.dtypes

id                float64
n_claims          float64
exposure          float64
area             category
vehicle_power     float64
vehicle_age       float64
driver_age        float64
bonus_malus       float64
vehicle_brand    category
vehicle_gas      category
density           float64
region           category
claim_amount      float64
frequency         float64
dtype: object

In [ ]:
# Since we have objects in the csv file we convert them to categories.
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype('category')

## Exploratory Data Analysis

In [17]:
df.describe()

,id,n_claims,exposure,vehicle_power,vehicle_age,driver_age,bonus_malus,density,claim_amount,frequency
count,6.795130e+05,679513.000000,679513.000000,679513.000000,679513.000000,679513.000000,679513.000000,679513.000000,6.795130e+05,679513.000000
mean,2.621743e+06,0.058554,0.529078,6.454486,7.043808,45.497617,59.784621,1794.052255,8.816493e+01,0.281781
std,1.641757e+06,0.279196,0.364378,2.050990,5.664855,14.140106,15.666953,3960.829098,5.810509e+03,4.731302
min,1.000000e+00,0.000000,0.002732,4.000000,0.000000,18.000000,50.000000,1.000000,0.000000e+00,0.000000
25%,1.157893e+06,0.000000,0.180000,5.000000,2.000000,34.000000,50.000000,92.000000,0.000000e+00,0.000000
50%,2.272111e+06,0.000000,0.490000,6.000000,6.000000,44.000000,50.000000,393.000000,0.000000e+00,0.000000
75%,4.046210e+06,0.000000,0.990000,7.000000,11.000000,55.000000,64.000000,1658.000000,0.000000e+00,0.000000
max,6.114330e+06,16.000000,2.010000,15.000000,100.000000,100.000000,230.000000,27000.000000,4.075401e+06,732.000000

In [ ]:
# Histogram plots of numerical columns.

num_cols = df.select_dtypes(include='float64').columns

for col in num_cols:
    plt.figure(figsize=(6,4))
    df[col].hist(bins=30)
    plt.title(f'Histogram of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.show()

In [ ]:
# Histogram plots of categorical columns.

cat_cols = df.select_dtypes(include='category').columns

for col in cat_cols:
    plt.figure(figsize=(6,4))
    df[col].value_counts().head(10).plot(kind="bar")
    plt.title(f"Top Categories of {col}")
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.show()